PROJECT_DIR=D:\\Fahmi\\Repository\\Sandbox\\java-automation
BASE_URL_DEV=https://fahmi-wiradika.github.io/
BASE_URL_LOC=""
BASE_URL_STG=""
BASE_URL_PRD=""
BASE_URL_SIMPLE_CRUD_DEV=http://localhost:3000/
BASE_URL_SIMPLE_CRUD_PROD=https://simple-crud-apps.vercel.app
GENERATE_ALLURE_HTML_REPORT=allure generate --single-file target/allure-results -o target/allure-report --clean